services:
  - type: web
    name: shl-recommender
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEYS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
